# Generated by Django 2.2.5 on 2019-09-08 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('can_start_today', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Importance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField()),
                ('abbreviation', models.CharField(max_length=1)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('abbreviation', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('sort_order', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Urgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField()),
                ('abbreviation', models.CharField(max_length=1)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sort_order', models.IntegerField()),
                ('abbreviation', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=200)),
                ('discretionary', models.BooleanField()),
                ('target_date', models.DateField(blank=True, null=True)),
                ('importance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timsy.Importance')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('duration', models.TimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timsy.Activity')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timsy.Place')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='importance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timsy.Importance'),
        ),
        migrations.AddField(
            model_name='activity',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timsy.Parent'),
        ),
        migrations.AddField(
            model_name='activity',
            name='urgency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timsy.Urgency'),
        ),
    ]
