# Generated by Django 5.1 on 2024-08-26 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timsy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdealDayTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='activityrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='importance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='urgency',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='IdealDayTemplateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('duration', models.TimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timsy.activity')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timsy.place')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timsy.idealdaytemplate')),
            ],
        ),
    ]
