# Generated by Django 5.1 on 2025-03-08 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timsy', '0002_idealdaytemplate_alter_activity_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdealDayTemplateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('duration', models.TimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timsy.activity')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timsy.place')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timsy.idealdaytemplate')),
            ],
        ),
    ]
