# Generated by Django 5.1 on 2025-05-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timsy', '0003_idealdaytemplaterecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrecord',
            name='start',
            field=models.DateTimeField(db_index=True),
        ),
    ]
