# Generated by Django 5.1 on 2025-05-17 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timsy', '0004_alter_activityrecord_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='discretionary',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='target_date',
        ),
    ]
