# Generated by Django 5.1 on 2025-05-17 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timsy', '0005_remove_parent_discretionary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='can_start_today',
        ),
    ]
