# Generated by Django 5.1 on 2025-05-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timsy', '0006_remove_activity_can_start_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='abbreviation',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
    ]
