# Generated by Django 5.1 on 2025-05-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timsy', '0007_alter_activity_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idealdaytemplaterecord',
            name='duration',
            field=models.DurationField(),
        ),
    ]
