# Generated by Django 5.1 on 2025-05-22 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timsy', '0008_alter_idealdaytemplaterecord_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timsy.idealdaytemplate')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'template')},
            },
        ),
        migrations.CreateModel(
            name='DailyPlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('duration', models.DurationField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timsy.activity')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timsy.place')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timsy.dailyplan')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
