# Generated by Django 5.1 on 2025-05-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timsy', '0009_dailyplan_dailyplanentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyplan',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='dailyplan',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
