# Generated by Django 5.1 on 2025-05-24 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timsy', '0010_alter_dailyplan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BlueprintEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('duration', models.TimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timsy.activity')),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timsy.blueprint')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timsy.place')),
            ],
        ),
    ]
