# Generated by Django 5.1 on 2025-05-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timsy', '0011_blueprint_blueprintentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyplan',
            name='template',
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='blueprints',
            field=models.ManyToManyField(blank=True, to='timsy.blueprint'),
        ),
        migrations.AlterField(
            model_name='dailyplanentry',
            name='duration',
            field=models.TimeField(),
        ),
    ]
