# Generated by Django 5.1 on 2025-05-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timsy', '0012_remove_dailyplan_template_dailyplan_blueprints_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idealdaytemplaterecord',
            name='template',
        ),
        migrations.RemoveField(
            model_name='idealdaytemplaterecord',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='idealdaytemplaterecord',
            name='place',
        ),
        migrations.DeleteModel(
            name='IdealDayTemplate',
        ),
        migrations.DeleteModel(
            name='IdealDayTemplateRecord',
        ),
    ]
