# Generated by Django 5.1 on 2025-05-26 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timsy', '0013_remove_idealdaytemplaterecord_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyplan',
            name='blueprints',
        ),
    ]
