# Generated by Django 5.1 on 2026-08-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timsy', '0015_remove_parent_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrecord',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
