# Generated by Django 5.1 on 2026-08-27 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timsy', '0016_activityrecord_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timsy.parent')),
            ],
            options={
                'indexes': [models.Index(fields=['parent', '-timestamp'], name='timsy_progr_parent__668e1f_idx')],
            },
        ),
    ]
