# Generated by Django 5.1 on 2026-08-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timsy', '0017_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
