# Generated by Django 5.1 on 2026-08-31 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timsy', '0018_dailyplan_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('horizon', models.CharField(choices=[('year', 'Year'), ('month', 'Month'), ('week', 'Week'), ('day', 'Day')], max_length=5)),
                ('horizon_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done')], default='open', max_length=4)),
                ('sort_order', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timsy.activity')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timsy.parent')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['horizon', 'horizon_date', 'status'], name='timsy_todoi_horizon_8a1b90_idx'), models.Index(fields=['parent', 'status', 'sort_order'], name='timsy_todoi_parent__5837de_idx')],
            },
        ),
    ]
