# Generated by Django 5.1 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timsy', '0019_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='program_order',
            field=models.IntegerField(default=0),
        ),
    ]
