# Generated by Django 5.1 on 2026-09-01 02:24

from django.db import migrations, models

PLACEHOLDER_ABBREVIATIONS = ('woph', 'ijgpph')


def mark_known_placeholders(apps, schema_editor):
    Activity = apps.get_model('timsy', 'Activity')
    Activity.objects.filter(abbreviation__in=PLACEHOLDER_ABBREVIATIONS).update(
        is_placeholder=True
    )


def unmark_known_placeholders(apps, schema_editor):
    Activity = apps.get_model('timsy', 'Activity')
    Activity.objects.filter(abbreviation__in=PLACEHOLDER_ABBREVIATIONS).update(
        is_placeholder=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('timsy', '0020_todoitem_program_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_placeholder',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_known_placeholders, unmark_known_placeholders),
    ]
