# Generated by Django 5.1 on 2026-09-04 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timsy', '0023_parent_state_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='anchor_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='interval_weeks',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='weekday_mask',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127)]),
        ),
    ]
