# Generated by Django 5.1 on 2026-09-04 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timsy', '0024_blueprint_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='WeeklyPlanAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timsy.parent')),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='timsy.weeklyplan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('weekly_plan', 'parent'), name='timsy_weeklyplanallocation_plan_parent_uniq')],
            },
        ),
    ]
